// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qluvvpflhsgtzjlgwffh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdXZ2cGZsaHNndHpqbGd3ZmZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDY5MzAsImV4cCI6MjA2MDMyMjkzMH0.hGT1kxDbqezcFL60tB2UQ0gtZjNdf5LXEpXvjWumQH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);